### PR TITLE
Missing responsive CSS columns

### PR DESCRIPTION
**Pull request by fonnets**
Following the opening of issues # 4 I managed to fix the reported problems. Please accept my changes. Thank you

### CODE REVIEW

**Comment by DemigodCode** [comment]
Thanks for this PR!

Glad that this package is being used.

**Comment by DemigodCode** [comment]
Hey, 

seems that some of the tests failed cause of the "\n" fix. Can you please take a look into it?

**Comment by DemigodCode** [comment]
What makes you thinking that?
There are no old GitHub Actions in history because github saves them a few months and then deletes them.
All Tests I see, are failing cause of the fixed "\n".

**Comment by fonnets** [comment]
In the development environment I reverted my changes and the tests continue to fail.
It seems that after an old change the test outputs were not updated.

**Comment by DemigodCode** [comment]
I've now enabled the manual run and that started the github action anyway.

The master branch is passing.
https://github.com/antibodies-online/bootstrap-email/actions/runs/9256176579

**Comment by DemigodCode** [comment]
Thanks for your contribution! I've fixed the failing unit tests.

**Comment by fonnets** [comment]
Thank you for accepting the changes! 

To get the latest version I had to force composer this way
`composer require antibodies-online/bootstrap-email dev-master#f47b3a7`, is this normal?

Grazie!

**Comment by DemigodCode** [comment]
Haven't yet released a new version. Will do that during the day.

**Comment by DemigodCode** [comment]
v1.0.4 now available in composer

**Comment by fonnets** [comment]
PERFECT 👏👏👏

**Pull request merged**
